# Generated by Django 6.0.6 on 2026-06-13 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['status']},
        ),
        migrations.RemoveField(
            model_name='task',
            name='complete',
        ),
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('To do', 'To do'), ('In Progress', 'In Progress'), ('Completed', 'Completed')], default='To do', max_length=20),
        ),
        migrations.AddField(
            model_name='task',
            name='uploaded_file',
            field=models.FileField(blank=True, null=True, upload_to='task_files/'),
        ),
    ]
