# Generated by Django 6.0.6 on 2026-06-14 06:47

import tasks.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_failedloginattempt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='uploaded_file',
            field=models.FileField(blank=True, null=True, upload_to=tasks.models.secure_file_path, validators=[tasks.models.validate_file_size]),
        ),
    ]
